#!/bin/sh

# Author: Jazz Yao-Tsung Wang <jazzwang.tw@gmail.com>
# - 2013-02-26 : First Draft
# distributed under the terms of the GNU GPL version 2 or (at your option) any later version
# see the file "COPYING" for details
# Ref: http://hands.com/d-i/squeeze/start.sh

set -e

## Ref: /usr/share/doc/opennebula/README.Debian.gz @ opennebula package

onehost list
onevnet list
onevm list
